pipeline {
    agent any

    tools {
        jdk 'jdk17'
        maven 'maven3'
    }

    stages {

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn package'
            }
        }

    }

    post {
        always {
            script {

                def jobName = env.JOB_NAME
                def buildNumber = env.BUILD_NUMBER
                def pipelineStatus = currentBuild.result ?: 'UNKNOWN'

                def statusColor = "#28a745"
                def statusIcon = "✅"

                if (pipelineStatus == "FAILURE") {
                    statusColor = "#dc3545"
                    statusIcon = "❌"
                } else if (pipelineStatus == "UNSTABLE") {
                    statusColor = "#ffc107"
                    statusIcon = "⚠️"
                } else if (pipelineStatus == "ABORTED") {
                    statusColor = "#6c757d"
                    statusIcon = "⛔"
                }

                def trigger = "Automated Trigger"
                try {
                    trigger = currentBuild.rawBuild.getCause(hudson.model.Cause.UserIdCause)?.userName ?: "Automated Trigger"
                } catch (Exception e) {
                    trigger = "Automated Trigger"
                }

                def body = """
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body style="margin:0;padding:20px;background:#f4f6f9;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" cellspacing="0" cellpadding="0">
<tr>
<td align="center">

<table width="650" cellspacing="0" cellpadding="0"
style="background:#ffffff;border-radius:10px;overflow:hidden;border:1px solid #dddddd;box-shadow:0 3px 10px rgba(0,0,0,0.1);">

<tr>
<td style="background:${statusColor};padding:25px;text-align:center;">
<h1 style="margin:0;color:white;font-size:28px;">
${statusIcon} Jenkins Build Notification
</h1>
</td>
</tr>

<tr>
<td style="padding:25px;text-align:center;">
<h2 style="margin:0;color:${statusColor};">
Build ${pipelineStatus.toUpperCase()}
</h2>
<p style="color:#666;font-size:15px;">
Your Jenkins pipeline has finished executing.
</p>
</td>
</tr>

<tr>
<td style="padding:0 30px 20px 30px;">

<table width="100%" cellspacing="0" cellpadding="8"
style="border-collapse:collapse;font-size:15px;">

<tr style="background:#f8f9fa;">
<td><b>Project</b></td>
<td>${jobName}</td>
</tr>

<tr>
<td><b>Build Number</b></td>
<td>#${buildNumber}</td>
</tr>

<tr style="background:#f8f9fa;">
<td><b>Status</b></td>
<td style="color:${statusColor};font-weight:bold;">
${pipelineStatus.toUpperCase()}
</td>
</tr>

<tr>
<td><b>Build URL</b></td>
<td>
<a href="${BUILD_URL}" style="color:#0d6efd;">
${BUILD_URL}
</a>
</td>
</tr>

<tr style="background:#f8f9fa;">
<td><b>Triggered By</b></td>
<td>${trigger}</td>
</tr>

<tr>
<td><b>Timestamp</b></td>
<td>${new Date().format("dd MMM yyyy HH:mm:ss")}</td>
</tr>

</table>

</td>
</tr>

<tr>
<td align="center" style="padding:25px;">

<a href="${BUILD_URL}"
style="
background:${statusColor};
color:white;
padding:14px 30px;
text-decoration:none;
font-weight:bold;
border-radius:6px;
display:inline-block;
font-size:16px;">
View Build Details
</a>

</td>
</tr>

<tr>
<td style="background:#f8f9fa;padding:18px;text-align:center;font-size:12px;color:#777;">

This email was automatically generated by
<b>Jenkins CI/CD</b>.

</td>
</tr>

</table>

</td>
</tr>
</table>

</body>
</html>
"""

                emailext(
                    subject: "${statusIcon} ${jobName} #${buildNumber} - ${pipelineStatus.toUpperCase()}",
                    body: body,
                    mimeType: "text/html",
                    to: "amateenxxxx@gmail.com",
                    from: "jenkins@example.com",
                    replyTo: "jenkins@example.com"
                )
            }
        }
    }
}
